# Generated by Django 6.0.4 on 2026-04-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('BANK', 'Bank Transfer'), ('CARD', 'Corporate Card'), ('CASH', 'Petty Cash'), ('UPI', 'Digital Payment / UPI')], max_length=20)),
                ('account_details', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.paymentmethod'),
        ),
    ]
