# Generated by Django 6.0.4 on 2026-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentmethod_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
